----1
SELECT NOME, ANO FROM FILMES

----2
SELECT * FROM FILMES ORDER BY ANO ASC;

----3
SELECT * FROM FILMES WHERE NOME = 'DE VOLTA PARA O FUTURO'


----4
SELECT * FROM FILMES WHERE ANO = '1997'

----5
SELECT * FROM FILMES WHERE ANO>2000

----6
SELECT * FROM FILMES WHERE DURACAO>100 AND DURACAO < 150
ORDER BY DURACAO ASC

----7
SELECT Ano, COUNT(*) AS Quantidade
FROM FILMES
GROUP BY Ano
ORDER BY QUANTIDADE DESC;


----8

SELECT * FROM ATORES
WHERE GENERO = 'M'


----9
SELECT * FROM ATORES
WHERE GENERO = 'F'
ORDER BY PRIMEIRONOME ASC

----10

SELECT 
 F.Nome,
 G.Genero
FROM FILMES AS F
INNER JOIN GENEROS G on F.ID = g.ID

----11

SELECT FILMES.NOME, GENEROS.GENERO
FROM FILMES
INNER JOIN GENEROS ON FILMES.ID = GENEROS.ID
WHERE GENEROS.ID = 10;

----12
SELECT FILMES.NOME, ATORES.PRIMEIRONOME, ATORES.ULTIMONOME, ELENCOFILME.PAPEL
FROM FILMES
INNER JOIN ELENCOFILME ON FILMES.ID = ELENCOFILME.IDFILME
INNER JOIN ATORES ON ELENCOFILME.IDATOR = ATORES.ID;